//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobile.Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked.
        /// </summary>
        internal static string Booked {
            get {
                return ResourceManager.GetString("Booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALL.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This customer is not have phone number.
        /// </summary>
        internal static string CanNotFoundPhoneNumber {
            get {
                return ResourceManager.GetString("CanNotFoundPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password?.
        /// </summary>
        internal static string Forget_Password_ {
            get {
                return ResourceManager.GetString("Forget Password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gascom Application.
        /// </summary>
        internal static string Gascom_Application {
            get {
                return ResourceManager.GetString("Gascom Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Customers.
        /// </summary>
        internal static string Get_Customers {
            get {
                return ResourceManager.GetString("Get Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Regions.
        /// </summary>
        internal static string Get_Regions {
            get {
                return ResourceManager.GetString("Get Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Direction.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone has not any map application.
        /// </summary>
        internal static string NoMapApplicationFound {
            get {
                return ResourceManager.GetString("NoMapApplicationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Request.
        /// </summary>
        internal static string PermissionRequest {
            get {
                return ResourceManager.GetString("PermissionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Region.
        /// </summary>
        internal static string Select_Region {
            get {
                return ResourceManager.GetString("Select Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no customer in your area.
        /// </summary>
        internal static string ThereIsNoAnyCustomerInYourRegion {
            get {
                return ResourceManager.GetString("ThereIsNoAnyCustomerInYourRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Status Customer.
        /// </summary>
        internal static string Update_Status_Customer {
            get {
                return ResourceManager.GetString("Update Status Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Percentage.
        /// </summary>
        internal static string WeightPercentage {
            get {
                return ResourceManager.GetString("WeightPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back.
        /// </summary>
        internal static string Welcome_Back {
            get {
                return ResourceManager.GetString("Welcome Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need this permission, so that we can find the closest order from your current location.
        /// </summary>
        internal static string WhyWeNeedThisPermission {
            get {
                return ResourceManager.GetString("WhyWeNeedThisPermission", resourceCulture);
            }
        }
    }
}
